services:
  - type: web
    name: fincal-evaluation-project
    buildCommand: cd client && npm install && npm run build
    startCommand: npm install -g serve && serve -s client/build
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://crm-management-api-14fg.onrender.com