services:
  - type: static
    name: fincal-evaluation-project
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/build
    envVars:
      - key: NODE_ENV
        value: production